/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.indianstatescensusanalyzer;

import org.junit.Test;

import com.bridgelabz.indianstatescensusanalyzer.IndianStatesCensusAnalyzer;

import static org.junit.Assert.*;

public class IndianStatesCensusAnalyzerTest {
}
