/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.indianstatescensusanalyzer;

import org.junit.Test;
import org.junit.rules.ExpectedException;

import com.bridgelabz.indianstatescensusanalyzer.StateCensusAnalyzer;

import static org.junit.Assert.*;

public class IndianStatesCensusAnalyzerTest {
	@Test
	public void loadIndiaCensusData_ValidCSVInput_NumberOfRows() {
		StateCensusAnalyzer analyzer = new StateCensusAnalyzer();
		int noOfLines = analyzer.loadIndiaCensusData("data.csv");
		assertEquals(2, noOfLines);
	}
	
	@Test 
	public void loadIndiaCensusData_givenWrongPath_returnsCorrectNumberRecords() {
    	try {
            StateCensusAnalyzer censusAnalyzer = new StateCensusAnalyzer();
            int numOfRecords = censusAnalyzer.loadIndiaCensusData("abc.csv");

        } catch (CensusAnalyzerException e) {
        	assertEquals(CensusAnalyzerException.ExceptionType.CENSUS_FILE_PROBLEM, e.type);
        }
    }
	
	 @Test
	    public void givenIndianCensusCSVFile_WhenCorrectPathButWrongFileFormat_ShouldThrowException() {
			
			try {
				StateCensusAnalyzer censusAnalyzer = new StateCensusAnalyzer();
				ExpectedException exceptionRule = ExpectedException.none();
				exceptionRule.expect(CensusAnalyzerException.class);
				censusAnalyzer.loadIndiaCensusData("data.txt");
			} 
			catch (CensusAnalyzerException e) {
				assertEquals(CensusAnalyzerException.ExceptionType.CSV_FILE_INTERNAL_ISSUES, e.type);
			}
	    }
}
